In [1]:
import numpy as np
import pandas as pd

In [6]:
df = pd.read_csv('play_tennis.csv')
df.head()

  day   outlook  temp humidity    wind play
0  D1     Sunny   Hot     High    Weak   No
1  D2     Sunny   Hot     High  Strong   No
2  D3  Overcast   Hot     High    Weak  Yes
3  D4      Rain  Mild     High    Weak  Yes
4  D5      Rain  Cool   Normal    Weak  Yes

In [7]:
df.drop(columns=['day'],inplace=True)

In [8]:
df

     outlook  temp humidity    wind play
0      Sunny   Hot     High    Weak   No
1      Sunny   Hot     High  Strong   No
2   Overcast   Hot     High    Weak  Yes
3       Rain  Mild     High    Weak  Yes
4       Rain  Cool   Normal    Weak  Yes
5       Rain  Cool   Normal  Strong   No
6   Overcast  Cool   Normal  Strong  Yes
7      Sunny  Mild     High    Weak   No
8      Sunny  Cool   Normal    Weak  Yes
9       Rain  Mild   Normal    Weak  Yes
10     Sunny  Mild   Normal  Strong  Yes
11  Overcast  Mild     High  Strong  Yes
12  Overcast   Hot   Normal    Weak  Yes
13      Rain  Mild     High  Strong   No

In [10]:
df['play'].value_counts()

play
Yes    9
No     5
Name: count, dtype: int64

In [11]:
py = 9/14
pn = 5/14

In [13]:
print(py)
print(pn)

0.6428571428571429
0.35714285714285715

In [14]:
pd.crosstab(df['outlook'], df['play'])

play      No  Yes
outlook
Overcast   0    4
Rain       2    3
Sunny      3    2

In [15]:
P_over_n = 0
P_r_n = 2/5
P_s_n = 3/5

P_o_y = 4/9
p_r_y = 3/9
P_s_y = 2/9

In [16]:
pd.crosstab(df['temp'], df['play'])

play  No  Yes
temp
Cool   1    3
Hot    2    2
Mild   2    4

In [17]:
P_cool_NO = 1/5
P_hot_NO = 2/5
P_Mild_N0 = 2/5

P_cool_yes = 3/9
P_Hot_Yes = 2/9
P_Mild_Yes = 4/9

In [18]:
pd.crosstab(df['humidity'], df['play'])

play      No  Yes
humidity
High       4    3
Normal     1    6

In [19]:
P_high_no = 4/5
P_normal_no = 1/5

P_high_yes = 3/9
P_normal_yes = 6/9

In [20]:
pd.crosstab(df['outlook'],df['play'])

play      No  Yes
outlook
Overcast   0    4
Rain       2    3
Sunny      3    2

In [21]:
P_Strong_no = 3/5
P_weak_no = 2/5

P_strong_yes = 3/9
P_weak_yes = 6/9

In [26]:
Pyes = py*P_s_y*P_Hot_Yes*P_high_yes*P_weak_yes
print(Pyes)

0.007054673721340388

In [25]:
Pno = pn*P_s_n*P_hot_NO*P_high_no*P_weak_no
print(Pno)

0.02742857142857143