In [1]:
import pandas as pd
import numpy as np

In [2]:
import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

In [4]:
df = pd.read_csv('heart.csv')

In [6]:
df.head(10)

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,52,1,0,125,212,0,1,168,0,1.0,2,2,3,0
1,53,1,0,140,203,1,0,155,1,3.1,0,0,3,0
2,70,1,0,145,174,0,1,125,1,2.6,0,0,3,0
3,61,1,0,148,203,0,1,161,0,0.0,2,1,3,0
4,62,0,0,138,294,1,1,106,0,1.9,1,3,2,0
5,58,0,0,100,248,0,0,122,0,1.0,1,0,2,1
6,58,1,0,114,318,0,2,140,0,4.4,0,3,1,0
7,55,1,0,160,289,0,0,145,1,0.8,1,1,3,0
8,46,1,0,120,249,0,0,144,0,0.8,2,0,3,0
9,54,1,0,122,286,0,0,116,1,3.2,1,2,2,0

In [12]:
x = df.iloc[:,0:-1]
y = df.iloc[:,-1]

In [13]:
from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=2)

In [14]:
x_train

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal
172,56,1,1,120,240,0,1,169,0,0.0,0,0,2
128,52,1,2,138,223,0,1,169,0,0.0,2,4,2
363,53,1,2,130,246,1,0,173,0,0.0,2,3,2
636,59,0,0,174,249,0,1,143,1,0.0,1,0,2
798,59,1,3,170,288,0,0,159,0,0.2,1,0,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...
299,52,1,1,120,325,0,1,172,0,0.2,2,0,2
534,54,0,2,108,267,0,0,167,0,0.0,2,0,2
584,55,1,0,132,353,0,1,132,1,1.2,1,1,3
493,55,1,0,132,353,0,1,132,1,1.2,1,1,3
527,62,0,0,124,209,0,1,163,0,0.0,2,0,2

In [15]:
y_train

172    1
128    1
363    1
636    0
798    0
      ..
299    1
534    1
584    0
493    0
527    1
Name: target, Length: 820, dtype: int64

In [16]:
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier

In [17]:
clf1 = LogisticRegression()
clf2 = DecisionTreeClassifier()

In [19]:
clf1.fit(x_train,y_train)
clf2.fit(x_train,y_train)

c:\Users\LENOVO THINKBOOK\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:406: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

DecisionTreeClassifier()

In [21]:
y_pred1 = clf1.predict(x_test)
y_pred2 = clf2.predict(x_test)

In [22]:
from sklearn.metrics import accuracy_score,confusion_matrix
print("Accuracy of Logistic Regression",accuracy_score(y_test,y_pred1))
print("Accuracy of Decision Trees",accuracy_score(y_test,y_pred2))

Accuracy of Logistic Regression 0.8390243902439024
Accuracy of Decision Trees 0.9804878048780488

In [24]:
confusion_matrix(y_test,y_pred1)

array([[82, 23],
       [10, 90]])

In [25]:
print("Logistic Regression Confusion Matrix\n")
pd.DataFrame(confusion_matrix(y_test,y_pred1),columns=list(range(0,2)))

Logistic Regression Confusion Matrix

    0   1
0  82  23
1  10  90

In [26]:
print('Decision Tree Confusion Matrix\n')
pd.DataFrame(confusion_matrix(y_test,y_pred2),columns=list(range(0,2)))

Decision Tree Confusion Matrix

     0    1
0  101    4
1    0  100

In [27]:
result = pd.DataFrame()
result['Actual Label'] = y_test
result['Logistic Regression Prediction'] = y_pred1
result['Decision Tree Prediction'] = y_pred2

In [28]:
result.sample(10)

     Actual Label  Logistic Regression Prediction  Decision Tree Prediction
842             0                               0                         0
911             0                               1                         0
900             0                               1                         0
193             1                               1                         1
644             1                               1                         1
700             1                               1                         1
844             0                               0                         0
867             1                               1                         1
917             1                               1                         1
143             1                               1                         1

In [29]:
from sklearn.metrics import recall_score,precision_score,f1_score

In [30]:
print("For Logistic regression Model")
print("-"*50)
cdf = pd.DataFrame(confusion_matrix(y_test,y_pred1),columns=list(range(0,2)))
print(cdf)
print("-"*50)
print("Precision - ",precision_score(y_test,y_pred1))
print("Recall - ",recall_score(y_test,y_pred1))
print("F1 score - ",f1_score(y_test,y_pred1))

For Logistic regression Model
--------------------------------------------------
    0   1
0  82  23
1  10  90
--------------------------------------------------
Precision -  0.7964601769911505
Recall -  0.9
F1 score -  0.8450704225352113

In [31]:
print("For DT Model")
print("-"*50)
cdf = pd.DataFrame(confusion_matrix(y_test,y_pred2),columns=list(range(0,2)))
print(cdf)
print("-"*50)
print("Precision - ",precision_score(y_test,y_pred2))
print("Recall - ",recall_score(y_test,y_pred2))
print("F1 score - ",f1_score(y_test,y_pred2))

For DT Model
--------------------------------------------------
     0    1
0  101    4
1    0  100
--------------------------------------------------
Precision -  0.9615384615384616
Recall -  1.0
F1 score -  0.9803921568627451

In [32]:
precision_score(y_test,y_pred1,average=None)

array([0.89130435, 0.79646018])

In [33]:
precision_score(y_test,y_pred2,average=None)

array([1.        , 0.96153846])

In [34]:
recall_score(y_test,y_pred2,average=None)

array([0.96190476, 1.        ])